version : '3'

services:
   db:
     image: postgres
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres

   webapp:
     depends_on:
       - db
     image: webapp:latest
     ports:
       - "8080:8080"
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
       POSTGRES_HOST: db

   scheduler:
     depends_on:
       - db
       - webapp
     image: scheduler:latest
     ports:
       - "9090:9090"
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
       POSTGRES_HOST: db
       REST_SERVER: webapp
