apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webingress
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: web.searchink.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 8080
