apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres.fullname" . }}-config
  namespace: default
data:
  postgres_user: {{ .Values.postgres.user }}
  postgres_password: {{ .Values.postgres.password }}
  postgres_host: {{ .Values.postgres.host }}
  rest_server: {{ .Values.rest.host }}