# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  user: postgres
  password: postgres
  host: postgres

rest:
  host: webapp

service:
  type: ClusterIP
  port: 5432